#!/bin/bash

set -e

SCRIPT_PATH=$(readlink $(which psnat3resolver))
SCRIPT_DIR_PATH=$(dirname "$SCRIPT_PATH")
USER_CONF_PATH=$SCRIPT_DIR_PATH/config/user.conf
MAIN_SCRIPT_PATH=$SCRIPT_DIR_PATH/psnat3resolver

source $USER_CONF_PATH

NETWORK_IDLE_TIMEOUT=${NETWORK_IDLE_TIMEOUT_HOURS}h
NETWORK_IDLE_MONITOR_INTERVAL=10m

MY_IP=$(hostname -I | awk '{print $1}')
PSNET_MONITOR_CMD="tcpdump -c 1 -qn src host $PS_IP and dst host not $MY_IP and not arp"

while true; do
    echo "Checking if a virtual link is enabled..."
    if systemctl is-enabled --quiet wg-quick@wg0; then
        echo "Virtual link is already enabled, skipping setup"
    else
        echo "Virtual link is not enabled"
        echo "Waiting for network activity from PS console ($PS_IP)..."
        eval "$PSNET_MONITOR_CMD"
        echo "Network activity observed, setting up a virtual link..."
        eval "$MAIN_SCRIPT_PATH up"
    fi

    echo "Network is UP"

    echo "Waiting for network idle to shut down, timeout is $NETWORK_IDLE_TIMEOUT..."
    while true; do
        if ! eval "timeout $NETWORK_IDLE_TIMEOUT $PSNET_MONITOR_CMD"; then
            echo "No PS console network activity observed during $NETWORK_IDLE_TIMEOUT. Shutting down network..."
            eval "$MAIN_SCRIPT_PATH down"
            break
        fi
        echo "PS console network activity observed, resetting idle timer..."
        sleep $NETWORK_IDLE_MONITOR_INTERVAL
    done
done 
